#!/usr/bin/env python3
"""Validate Phase 8 ECHO SDK templates against scanner-facing contracts."""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import echo_sdk
import generate_echo_reports


FIXTURE_MODULE_ID = "echosdkfixturecontent"
FIXTURE_PACK_ID = "echo_sdk_fixture_pack"
STUB_TEMPLATE_EXPECTATIONS = {
    "echo-addon-ui-surface": [
        "addons/{{module_id}}/docs/client-isolation.md",
        "addons/{{module_id}}/src/main/java/{{package_path}}/clientboundary/{{class_name}}ClientBoundary.java",
        "addons/{{module_id}}/src/main/resources/data/{{module_id}}/ui/{{module_id}}_surface.json",
    ],
    "echo-schema": [
        "addons/{{module_id}}/src/main/java/{{package_path}}/contract/{{class_name}}SchemaContract.java",
        "addons/{{module_id}}/src/main/resources/data/{{module_id}}/schemas/{{module_id}}.schema.json",
    ],
    "echo-metadata": [
        "addons/{{module_id}}/src/main/java/{{package_path}}/contract/{{class_name}}MetadataContract.java",
        "addons/{{module_id}}/src/main/resources/data/{{module_id}}/metadata/{{module_id}}.metadata.json",
    ],
    "echo-report": [
        "addons/{{module_id}}/src/main/java/{{package_path}}/contract/{{class_name}}ReportEnvelopeContract.java",
        "addons/{{module_id}}/src/main/resources/data/{{module_id}}/reports/{{module_id}}.report.json",
    ],
    "echo-addon-ai-tool": [
        "addons/{{module_id}}/src/main/java/{{package_path}}/contract/{{class_name}}AiToolContract.java",
        "addons/{{module_id}}/src/main/resources/data/{{module_id}}/ai_tools/{{module_id}}.ai-tool.json",
    ],
    "echo-addon-bridge-tool": [
        "addons/{{module_id}}/src/main/java/{{package_path}}/contract/{{class_name}}BridgeToolContract.java",
        "addons/{{module_id}}/src/main/resources/data/{{module_id}}/bridge_tools/{{module_id}}.bridge-tool.json",
    ],
}
FORBIDDEN_COMMON_IMPORTS = (
    "net.minecraft.client",
    "com.mojang.blaze3d",
    "net.minecraftforge",
    "net.fabricmc",
)
NATIVE_TEMPLATE_IDS = (
    "echo-native-addon",
    "echo-native-config-example",
    "echo-native-event-example",
    "echo-native-module",
    "echo-native-packet-example",
    "echo-native-registry-example",
    "echo-native-screen-hud-example",
    "echo-native-testkit-example",
    "echo-native-worldgen-example",
    "new-addon-template",
    "native-module-template",
)
FORBIDDEN_NATIVE_JAVA_MARKERS = (
    "dev.echo.nativeplatform.loader",
    "net.neoforged",
    "net.minecraftforge",
    "net.fabricmc",
    "EchoNativeAddonRuntime",
)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def prepare_fixture_root(root: Path) -> Path:
    fixture_root = root / "build" / "echo-sdk-fixtures"
    resolved_fixture = fixture_root.resolve()
    try:
        resolved_fixture.relative_to((root / "build").resolve())
    except ValueError as exc:
        raise ValueError(f"Refusing to clean fixture output outside build/: {resolved_fixture}") from exc
    if fixture_root.exists():
        shutil.rmtree(fixture_root)
    fixture_root.mkdir(parents=True)
    write_text(
        fixture_root / "settings.gradle",
        "def echoBetaAddons = ['echosdkfixturecontent']\n"
        "def echoReleaseAddons = []\n",
    )
    write_text(
        fixture_root / "gradle.properties",
        "minecraft_version=26.1.2\n"
        "minecraft_version_range=[26.1.2,26.2)\n"
        "neo_version=26.1.2.29-beta\n"
        "mod_id=echosdkfixturehost\n"
        "mod_name=ECHO SDK Fixture Host\n"
        "mod_version=1.0.0\n"
        "mod_group_id=com.knoxhack.echo.sdk.fixturehost\n",
    )
    write_text(fixture_root / "build.gradle", "// ECHO SDK fixture root. Generated by validate_echo_sdk_templates.py.\n")
    write_text(fixture_root / "docs" / "echo" / "sdk" / "README.md", "# ECHO SDK Fixture\n")
    write_text(fixture_root / "core" / "echocore" / "build.gradle", "// ECHO SDK fixture echocore.\n")
    write_text(
        fixture_root / "core" / "echocore" / "gradle.properties",
        "mod_id=echocore\n"
        "mod_name=ECHO Core Fixture\n"
        "mod_version=1.0.0\n",
    )
    write_text(
        fixture_root / "core" / "echocore" / "src" / "main" / "resources" / "META-INF" / "echo.mod.json",
        json.dumps(
            {
                "schema": "echo.mod.v1",
                "id": "echocore",
                "name": "ECHO Core Fixture",
                "version": "1.0.0",
                "type": "core",
                "kind": "core",
                "role": "core",
                "official": True,
                "trustLevel": "official",
                "standalone": True,
                "side": "common",
                "requires": [],
                "optional": [],
                "provides": ["echo.core"],
                "consumes": [],
                "gameModes": [],
                "permissions": ["echo.core"],
                "assets": [],
                "transforms": [],
                "access": {},
                "apiStability": "stable",
            },
            indent=2,
            ensure_ascii=True,
        )
        + "\n",
    )
    return fixture_root


def render_fixture(root: Path, fixture_root: Path) -> list[str]:
    args = SimpleNamespace(
        module_id=FIXTURE_MODULE_ID,
        role="content_feature",
        kind_value=None,
        feature_id=None,
        class_name=None,
        display_name="ECHO SDK Fixture Content",
    )
    rendered = echo_sdk.render_template(
        root,
        "echo-addon-content",
        fixture_root,
        args,
        "addon",
        force=True,
        dry_run=False,
    )
    return [item.target.relative_to(fixture_root).as_posix() for item in rendered]


def render_pack_fixture(root: Path, fixture_root: Path) -> list[str]:
    args = SimpleNamespace(
        pack_id=FIXTURE_PACK_ID,
        role="pack_root",
        kind_value="official_pack",
        feature_id=None,
        class_name=None,
        display_name="ECHO SDK Fixture Pack",
    )
    rendered = echo_sdk.render_template(
        root,
        "echo-pack-profile",
        fixture_root,
        args,
        "pack",
        force=True,
        dry_run=False,
    )
    return [item.target.relative_to(fixture_root).as_posix() for item in rendered]


def validate_json_file(path: Path, errors: list[str]) -> dict[str, Any]:
    if not path.is_file():
        errors.append(f"Missing JSON file: {path.as_posix()}")
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        errors.append(f"Invalid JSON in {path.as_posix()}: {exc}")
        return {}
    if not isinstance(payload, dict):
        errors.append(f"JSON root must be an object: {path.as_posix()}")
        return {}
    return payload


def validate_fixture_files(fixture_root: Path, errors: list[str]) -> None:
    addon_root = fixture_root / "addons" / FIXTURE_MODULE_ID
    required_files = [
        "build.gradle",
        "gradle.properties",
        f"src/main/java/com/knoxhack/echo/sdk/{FIXTURE_MODULE_ID}/EchoSdkContentAddon.java",
        "src/main/resources/META-INF/echo.mod.json",
        "src/main/resources/META-INF/echo.ai.json",
        "src/main/templates/META-INF/neoforge.mods.toml",
        "README.md",
        f"docs/{FIXTURE_MODULE_ID}.md",
        f"src/test/validation/{FIXTURE_MODULE_ID}.validation.json",
    ]
    for relative in required_files:
        if not (addon_root / relative).is_file():
            errors.append(f"Rendered fixture is missing {relative}")
    echo_mod = validate_json_file(addon_root / "src/main/resources/META-INF/echo.mod.json", errors)
    echo_ai = validate_json_file(addon_root / "src/main/resources/META-INF/echo.ai.json", errors)
    if echo_mod.get("id") != FIXTURE_MODULE_ID:
        errors.append("echo.mod.json id does not match fixture module id")
    if echo_mod.get("role") != "content_feature":
        errors.append("echo.mod.json role does not reflect the requested role")
    if not echo_mod.get("provides"):
        errors.append("echo.mod.json must declare at least one provided feature")
    if echo_ai.get("module") != FIXTURE_MODULE_ID:
        errors.append("echo.ai.json module does not match fixture module id")
    if not echo_ai.get("safeEditZones"):
        errors.append("echo.ai.json must declare safeEditZones")
    if not echo_ai.get("recommendedAgentLanes"):
        errors.append("echo.ai.json must declare recommendedAgentLanes")


def validate_pack_fixture_files(fixture_root: Path, errors: list[str]) -> None:
    pack_root = fixture_root / "packs" / "echo-sdk-fixture-pack"
    required_files = [
        "echo.pack.json",
        "echo.ai.json",
        "README.md",
    ]
    for relative in required_files:
        if not (pack_root / relative).is_file():
            errors.append(f"Rendered pack fixture is missing {relative}")
    if not (fixture_root / "docs" / f"{FIXTURE_PACK_ID}.md").is_file():
        errors.append("Rendered pack fixture is missing docs stub")
    if not (fixture_root / "src/test/validation" / f"{FIXTURE_PACK_ID}.validation.json").is_file():
        errors.append("Rendered pack fixture is missing validation stub")
    pack_profile = validate_json_file(pack_root / "echo.pack.json", errors)
    pack_ai = validate_json_file(pack_root / "echo.ai.json", errors)
    if pack_profile.get("schemaVersion") != "echo.pack.v1":
        errors.append("echo.pack.json schemaVersion must be echo.pack.v1")
    if pack_profile.get("id") != FIXTURE_PACK_ID:
        errors.append("echo.pack.json id does not match fixture pack id")
    if pack_profile.get("type") != "official_pack":
        errors.append("echo.pack.json type does not reflect requested pack kind")
    if not pack_profile.get("requiredModules"):
        errors.append("echo.pack.json must declare requiredModules")
    if not pack_profile.get("requiredFeatures"):
        errors.append("echo.pack.json must declare requiredFeatures")
    if pack_ai.get("module") != FIXTURE_PACK_ID:
        errors.append("pack echo.ai.json module does not match fixture pack id")


def validate_registration_plan(root: Path, fixture_root: Path, errors: list[str]) -> dict[str, Any]:
    settings_path = root / "settings.gradle"
    before = settings_path.read_text(encoding="utf-8") if settings_path.is_file() else ""
    plan = echo_sdk.registration_plan(root, FIXTURE_MODULE_ID, fixture_root)
    after = settings_path.read_text(encoding="utf-8") if settings_path.is_file() else ""
    if before != after:
        errors.append("registration plan mutated the real settings.gradle")
    if plan.get("schema") != "echo.sdk.registration_plan.v1":
        errors.append("registration plan schema mismatch")
    if plan.get("mutatesSettingsGradle") is not False:
        errors.append("registration plan must declare mutatesSettingsGradle=false")
    if plan.get("writesFiles") is not False:
        errors.append("registration plan must declare writesFiles=false")
    if not plan.get("proposedSettingsGradleLines"):
        errors.append("registration plan must include proposed settings.gradle lines")
    if "addons/echosdkfixturecontent" not in str(plan.get("targetAddonPath", "")):
        errors.append("registration plan targetAddonPath must point at the generated fixture addon")
    return plan


def validate_template_specific_stubs(root: Path, fixture_root: Path, errors: list[str]) -> list[str]:
    rendered_stub_files: list[str] = []
    for template_id, expected_patterns in STUB_TEMPLATE_EXPECTATIONS.items():
        module_id = f"echosdkfixture{template_id.replace('echo-', '').replace('addon-', '').replace('-', '')}"[:48]
        args = SimpleNamespace(
            module_id=module_id,
            role=None,
            kind_value=None,
            feature_id=None,
            class_name=None,
            display_name=None,
        )
        output_root = fixture_root / "stub-dry-runs" / template_id
        rendered = echo_sdk.render_template(root, template_id, output_root, args, "addon", force=True, dry_run=True)
        rendered_targets = {item.target.relative_to(output_root).as_posix() for item in rendered}
        manifest = echo_sdk.template_manifest(root, template_id)
        tokens = echo_sdk.build_tokens(manifest, args, "addon")
        for pattern in expected_patterns:
            expected = echo_sdk.render_tokens(pattern, tokens)
            rendered_stub_files.append(f"{template_id}:{expected}")
            if expected not in rendered_targets:
                errors.append(f"{template_id} did not render expected template-specific stub {expected}")
    return sorted(rendered_stub_files)


def validate_static_compile_orientation(fixture_root: Path, errors: list[str]) -> dict[str, Any]:
    addon_root = fixture_root / "addons" / FIXTURE_MODULE_ID
    java_files = sorted((addon_root / "src/main/java").rglob("*.java"))
    for path in java_files:
        text = path.read_text(encoding="utf-8")
        for forbidden in FORBIDDEN_COMMON_IMPORTS:
            if forbidden in text:
                errors.append(f"Generated fixture Java file imports forbidden common/client API marker {forbidden}: {path.as_posix()}")
    return {
        "status": "static_only",
        "checkedJavaFiles": len(java_files),
        "blockedReason": "Generated fixtures are intentionally not registered into the real workspace; isolated NeoForge compile proof remains a future SDK harness task.",
    }


def validate_native_template_exports(root: Path, fixture_root: Path, errors: list[str]) -> list[dict[str, Any]]:
    reports: list[dict[str, Any]] = []
    for template_id in NATIVE_TEMPLATE_IDS:
        module_id = f"echosdk{template_id.replace('echo-', '').replace('-', '')}"[:48]
        args = SimpleNamespace(
            module_id=module_id,
            role=None,
            kind_value=None,
            feature_id=None,
            class_name=None,
            display_name=None,
        )
        output_root = fixture_root / "native-template-exports" / template_id
        rendered = echo_sdk.render_template(root, template_id, output_root, args, "addon", force=True, dry_run=False)
        rendered_targets = {item.target.relative_to(output_root).as_posix() for item in rendered}
        addon_root = output_root / "addons" / module_id
        build_file = addon_root / "build.gradle"
        descriptor_file = addon_root / "src/main/resources/META-INF/echo.mod.json"
        java_files = sorted((addon_root / "src/main/java").rglob("*.java"))

        if f"addons/{module_id}/build.gradle" not in rendered_targets:
            errors.append(f"{template_id} did not render a Gradle build file")
        if f"addons/{module_id}/src/main/resources/META-INF/echo.mod.json" not in rendered_targets:
            errors.append(f"{template_id} did not render META-INF/echo.mod.json")
        if not java_files:
            errors.append(f"{template_id} did not render a Java entrypoint")

        entrypoint_files = [path for path in java_files if path.parent.name != "examples"]
        for java_file in java_files:
            text = java_file.read_text(encoding="utf-8")
            for forbidden in FORBIDDEN_NATIVE_JAVA_MARKERS:
                if forbidden in text:
                    errors.append(f"{template_id} rendered forbidden Native Java marker {forbidden}: {java_file.as_posix()}")
        for java_file in entrypoint_files:
            text = java_file.read_text(encoding="utf-8")
            if "EchoNativeModuleEntrypoint" not in text:
                errors.append(f"{template_id} entrypoint must implement EchoNativeModuleEntrypoint: {java_file.as_posix()}")
            if "EchoNativeMutationReceipt" not in text:
                errors.append(f"{template_id} entrypoint must demonstrate typed mutation receipts: {java_file.as_posix()}")

        descriptor = validate_json_file(descriptor_file, errors)
        access = descriptor.get("access") if isinstance(descriptor.get("access"), dict) else {}
        native_classpath = access.get("nativeClasspath") if isinstance(access.get("nativeClasspath"), list) else []
        if descriptor.get("entrypoint") is None:
            errors.append(f"{template_id} descriptor must declare entrypoint")
        if "addon.jar" not in native_classpath:
            errors.append(f"{template_id} descriptor must declare access.nativeClasspath ['addon.jar']")

        build_text = build_file.read_text(encoding="utf-8") if build_file.is_file() else ""
        if "packageEchoNativeAddon" not in build_text:
            errors.append(f"{template_id} build must expose packageEchoNativeAddon")
        if "verifyNativeAddonBoundaries" not in build_text:
            errors.append(f"{template_id} build must verify Native addon import boundaries")

        reports.append({
            "templateId": template_id,
            "moduleId": module_id,
            "renderedFileCount": len(rendered_targets),
            "javaFileCount": len(java_files),
            "hasDescriptor": descriptor_file.is_file(),
            "hasPackageTask": "packageEchoNativeAddon" in build_text,
        })
    return reports


def validate_fixture_reports(fixture_root: Path, errors: list[str]) -> None:
    context = generate_echo_reports.collect_context(fixture_root, "beta", "sdk_fixture", "not_run", "ashfall", "")
    reports = generate_echo_reports.create_reports(context)
    generate_echo_reports.write_reports(fixture_root, reports, context)
    scanned = generate_echo_reports.load_json(fixture_root / "reports/echo/scanned-modules.json")
    module_graph = generate_echo_reports.load_json(fixture_root / "reports/echo/module-graph.json")
    scanned_modules = scanned.get("data", {}).get("scannedModules", {}).get("modules", [])
    graph_nodes = module_graph.get("data", {}).get("moduleGraph", {}).get("nodes", [])
    scanned_ids = {module.get("moduleId") for module in scanned_modules if isinstance(module, dict)}
    graph_ids = {node.get("id") for node in graph_nodes if isinstance(node, dict)}
    if FIXTURE_MODULE_ID not in scanned_ids:
        errors.append("Rendered fixture module did not appear in workspace scan")
    if FIXTURE_MODULE_ID not in graph_ids:
        errors.append("Rendered fixture module did not appear in module graph")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    errors: list[str] = []
    validation = echo_sdk.validate_templates(root)
    errors.extend(validation.get("errors", []))
    fixture_root = prepare_fixture_root(root)
    rendered_files = render_fixture(root, fixture_root)
    rendered_pack_files = render_pack_fixture(root, fixture_root)
    rendered_stub_files = validate_template_specific_stubs(root, fixture_root, errors)
    validate_fixture_files(fixture_root, errors)
    validate_pack_fixture_files(fixture_root, errors)
    registration = validate_registration_plan(root, fixture_root, errors)
    compile_proof = validate_static_compile_orientation(fixture_root, errors)
    native_exports = validate_native_template_exports(root, fixture_root, errors)
    validate_fixture_reports(fixture_root, errors)
    payload = {
        "schema": "echo.sdk.template_validation.v1",
        "status": "PASS" if not errors else "FAILED",
        "templateCount": validation.get("templateCount", 0),
        "validatedTemplates": validation.get("validatedTemplates", []),
        "fixtureRoot": "build/echo-sdk-fixtures",
        "fixtureModuleId": FIXTURE_MODULE_ID,
        "fixturePackId": FIXTURE_PACK_ID,
        "renderedFileCount": len(rendered_files),
        "renderedPackFileCount": len(rendered_pack_files),
        "templateSpecificStubCount": len(rendered_stub_files),
        "registrationPlan": registration,
        "compileProof": compile_proof,
        "nativeTemplateExports": native_exports,
        "settingsGradleModified": False,
        "errors": errors,
    }
    output = json.dumps(payload, indent=2, ensure_ascii=True)
    write_text(root / "reports" / "echo" / "native" / "sdk-template-validation.json", output + "\n")
    print(output)
    return 0 if not errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
