plugins {
    id 'java'
    id 'dev.echo.native.echo-sdk-gradle-plugin' version '1.0.0-RC1'
}

group = 'com.example'
version = '1.0.0'

repositories {
    mavenLocal()
    maven { url 'https://maven.echo.dev/rc' }
    mavenCentral()
}

dependencies {
    implementation 'dev.echo.native:echoaddonapi:1.0.0-RC1'
    implementation 'dev.echo.native:echo-native-contracts:1.0.0-RC1'
    testImplementation 'dev.echo.native:echo-native-testkit:1.0.0-RC1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

test {
    useJUnitPlatform()
}
